### PR TITLE
Added silent setting to prevent raising exceptions

### PR DESCRIPTION
**Pull request by cjermain**
When running `sshtunnel` as a thread, exceptions from the handler are printed to the console directly. This is often not a desired feature, since the console will become cluttered by error messages for any connection in error -- even when the majority of connections are successful. This pull request adds a boolean flag `silent`, that suppresses the exceptions while continuing to correctly log these errors using the Python logging module.

With the addition of the `logging.raiseExceptions` flag, `sshtunnel` can now be operated in a completely silent way.

```python
import paramiko
from sshtunnel import *
import logging

logging.raiseExceptions = False

server = SSHTunnelForwarder(
    ssh_address=('1.2.3.4', 22),
    ssh_username='username',
    ssh_private_key=paramiko.RSAKey.from_private_key_file('...'),
    remote_bind_address=('127.0.0.1', 80),
    local_bind_address=('127.0.0.1', 80),
    silent=True,
)

server.start()
```

### CODE REVIEW

**Comment by fernandezcuesta** [comment]
IMHO hiding an exception is not the correct way to sort this out, since it may mask errors to the users. Exceptions should be handled and console logging level is always configurable.

**Comment by cjermain** [comment]
My solution only hides exceptions raised by the Handler. Since this is executed in a thread, the main program does not have access to handling the exception and the program will continue to work despite raised exceptions. This is why I suggest to hide the exceptions from the Handler so that console output is not cluttered by exceptions that can not be handled anyways. Instead, you can still log the error message with the Python logging module as you suggest, which can be configured to write to stdout, a file, etc.

The `logging.raiseExceptions = False` was provided for completeness, since a console message is otherwise still displayed by the `logging` module.

**Comment by cjermain** [comment]
@fernandezcuesta, does my explanation answer your concerns about exception hiding?

@pahaz, what do you think about including this feature? I'm hoping to release a console program soon that uses `sshtunnel`, and this feature is necessary to prevent the console from being significantly cluttered.

**Comment by fernandezcuesta** [comment]
Yes, it makes sense to do it while in the threads.
You could also move the first assert inside the try: clause and catch AssertionError too. Otherwise when self.remote_address is not a tuple it will raise an error regardless of logging.raiseExceptions.

**Comment by cjermain** [comment]
What is the purpose of that assertion ([line 105](https://github.com/cjermain/sshtunnel/blob/master/sshtunnel.py#L105))? It appears that [line 240](https://github.com/cjermain/sshtunnel/blob/master/sshtunnel.py#L240) also asserts the same thing. Is Handler.remote_address expected to have changed since the Handler is constructed?

**Comment by cjermain** [comment]
@pahaz, any update on whether this will get included in the next version?

**Comment by pahaz** [comment]
@cjermain, Hi. I have to agree with @fernandezcuesta. You must use logging level for hiding exceptions.

**Comment by pahaz** [comment]
> What is the purpose of that assertion (line 105)? It appears that line 240 also asserts the same thing. Is Handler.remote_address expected to have changed since the Handler is constructed?

Write an argument guards is the good practice.

**Comment by cjermain** [comment]
> You must use logging level for hiding exceptions.

I'm confused about what you mean. Currently the exceptions being raised in _BaseHandler ([Line 115](https://github.com/pahaz/sshtunnel/blob/64f5d989ae8bdf738a2b5b54192461526784a839/sshtunnel.py#L115) and [Line 121](https://github.com/pahaz/sshtunnel/blob/64f5d989ae8bdf738a2b5b54192461526784a839/sshtunnel.py#L121)) can not be handled by the main program because they are executed in a thread (SSHTunnelForwarder). Since they are already being handled by the Python logging package, is it worth raising the exceptions in the first place?

**Comment by pahaz** [comment]
Sorry. I wrote answer in a deep night :)

The true way is create custom `Handler` class inherited form `_BaseHandler` with overridden `handle` method. https://github.com/pahaz/sshtunnel/blob/64f5d989ae8bdf738a2b5b54192461526784a839/sshtunnel.py#L98 

    class YouCustomSilentHandlerClass(_BaseHandler):
        # write logic ...
    
    
    class MySSHTunnelForwarder(SSHTunnelForwarder):
        def __init__(self,
                     ssh_address=None,
                     ssh_host_key=None,
                     ssh_username=None,
                     ssh_password=None,
                     ssh_private_key=None,
                     remote_bind_address=None,
                     local_bind_address=None,
                     threaded=False):
            
            threading.Thread.__init__(self)
            
            self._local_bind_address = local_bind_address
            self._remote_bind_address = remote_bind_address
            self._ssh_private_key = ssh_private_key
            self._ssh_password = ssh_password
            self._ssh_username = ssh_username
            self._ssh_host_key = ssh_host_key
            self._transport = paramiko.Transport(ssh_address)
            
            # HOTFIX
            Handler = make_ssh_forward_handler(remote_bind_address, ssh_transport_, base_ssh_forward_handler=YouCustomSilentHandlerClass)
            Server = _ThreadingForwardServer if threaded else _ForwardServer
            server = Server(local_bind_address, Handler)
            
            self._server = server
            self._is_started = False

Not so cool but still work :(

You may be confused by use private class. This is problem.

Need add `make_server` and `make_transport` methods to `SSHTunnelForwarder`. And add `base_ssh_forward_handler` argument to `make_ssh_forward_server` function. After this fixes you may use something like this:

    class YouCustomSilentHandlerClass(_BaseHandler):
        def handler(self):
            try:
                super(YouCustomSilentHandlerClass, self).handler()
            except HandlerSSHTunnelForwarderError:
                pass
    
    
    class MySSHTunnelForwarder(SSHTunnelForwarder):
        SSH_FORWARD_HANDLER = YouCustomSilentHandlerClass
        
        def make_server(self):
            return make_ssh_forward_server(
                self._remote_bind_address,
                self._local_bind_address,
                self._transport,
                is_threading=threaded,
                base_ssh_forward_handler=self.SSH_FORWARD_HANDLER,
            )

**Comment by cjermain** [comment]
Ok. I understand your solution, but I'm not clear on why raising a Python exception in a thread is proper practice as @fernandezcuesta and I discussed above. Shouldn't those errors only be recorded by the Python logging module in that case?

**Comment by pahaz** [comment]
@cjermain, do you want re raise exception? This is normal behavior, in our case if we have a one bad client we don't want stopping server working.

**Pull request closed without merging**
