### PR TITLE
Fix Thread daemon mode for < Python 3.3

### PR DESCRIPTION
**Pull request by lewisthompson**

### CODE REVIEW

**Comment by ewrogers** [comment]
Just had this same issue the other day, +1 on the fix. Only suggestion I would have is to retain the `self.daemon_forward_servers` flag:
```
threads = [
            threading.Thread(
                target=self.serve_forever_wrapper, args=(_srv,),
                name="Srv-" + address_to_str(_srv.local_address))
            for _srv in self._server_list
            ]

        for thread in threads:
            thread.daemon = self.daemon_forward_servers
            thread.start()
```

**Comment by lewisthompson** [comment]
@ewrogers Absolutely agree.  I've just updated the branch with your suggestion

**Comment by pahaz** [comment]
Thanks!

**Comment by pahaz** [comment]
@ewrogers, @lewisthompson I've added you to the list of contributors.

**Pull request merged**
