### PR TITLE
Add `entry_points` to `setup.py`

### PR DESCRIPTION
**Pull request by fernandezcuesta**
Added `sshtunnel` to `console_scripts`, so it can be invoked directly from CLI.

### CODE REVIEW

**Comment by pahaz** [comment]
Can you remove last commit for merging? The last changes don't solve the problem with default port. 
I created the issuse https://github.com/pahaz/sshtunnel/issues/19 for this problem.

**Comment by fernandezcuesta** [comment]
Hi pahaz,
apologies, it shouldn't break anything now. As mentioned, default port 22 goes in CLI arguments only.

**Comment by pahaz** [comment]
@fernandezcuesta, Hi, I can`t merge your changes. Can you rebase from master? and now default port issuse is fixed by: https://github.com/pahaz/sshtunnel/commit/18d972ca3dfd8094f7d0b7da2b2882620596531b

**Comment by fernandezcuesta** [comment]
should be up to date now

**Comment by pahaz** [comment]
Sorry, I missed the update. Great! Thanks again!

**Pull request merged**
