### PR TITLE
Allow host_pkey_directories to be None

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
As we have the DEFAULT_SSH_DIRECTORY

### CODE REVIEW

**Comment by fernandezcuesta** [comment]
This doesn't allow skipping key loading. Currently by setting `host_pkey_directories` no `None` will skip that.

**Comment by NielsZeilemaker** [comment]
I agree, but then the default value of host_pkey_directories should be `''` to be able to use the `DEFAULT_SSH_DIRECTORY`

**Comment by fernandezcuesta** [comment]
Exactly, by default (`None`) it is disabled, but if you set an empty list you'll be using `DEFAULT_SSH_DIRECTORY`.

**Comment by NielsZeilemaker** [comment]
Then, the documentation is a bit off:

``` 
host_pkey_directories (list):

            Look for pkeys in folders on this list, for example ['~/.ssh'].

            An empty list disables this feature
```

As an empty list actually enables this feature

**Comment by fernandezcuesta** [comment]
then you found a bug (in the documentation) :+1:

**Pull request closed without merging**
