### PR TITLE
Fix private keys are not found on Linux/Windows

### LINKED ISSUE #161: User private keys are not found in default directory
This line of code

https://github.com/pahaz/sshtunnel/blob/bd4ae32344a3a68ce27b1ad27c992687613b3182/sshtunnel.py#L1021

prevents the `or` at

https://github.com/pahaz/sshtunnel/blob/bd4ae32344a3a68ce27b1ad27c992687613b3182/sshtunnel.py#L1026

to kick in and allow for `DEFAULT_SSH_DIRECTORY` to be searched. With the result that no keys are found even when there are plenty!

### PR DESCRIPTION
**Pull request by fernandezcuesta**

### CODE REVIEW

**Comment by pahaz** [comment]
https://github.com/pahaz/sshtunnel/issues/126 this may be related to the same problem

**Comment by pahaz** [comment]
Sorry for my commit :) feel free to delete it. You are the first %)

**Comment by fernandezcuesta** [comment]
No problem, I'm booking some time later on and fix this issue. Not as easy as deleting the if condition though.

**Comment by pahaz** [comment]
Probably we also can use `ssh_private_key_password` for the default ssh key location. It's also may be helpful.

```
tunnel = SSHTunnelForwarder(
    SSH_SERVER_ADDRESS,
    ssh_username=SSH_SERVER_USERNAME,
    ssh_private_key_password=SSH_SERVER_PKEY_PASS,
    remote_bind_address=SSH_SERVER_REMOTE_SIDE_ADDRESS,
)
```

**Comment by pahaz** [comment]
And also, https://github.com/pahaz/sshtunnel/issues/145 is also may be fixed. I think we can check the `~/.ssh` path first and then check `~/ssh` for windows. But I'm not sure 🤔

**Comment by fernandezcuesta** [comment]
regarding #145, I agree with setting `~/.ssh` as default config folder for windows as well.

**Pull request merged**
