### PR TITLE
Allow several tunnels at once

### PR DESCRIPTION
**Pull request by fernandezcuesta**
Hi, modifications done on top of latest version.
I tried to keep backwards compatibility as much as possible, but had to rename `open` to `open_tunnel` since builtin's used in __init__.

### CODE REVIEW

**Comment by pahaz** [comment]
Thanks again. Byt, can you answer to the my questions?
What the reason opening several tunnels?
Can you create several tunnels support on top of current project?
I think that realy good improvement is create a new project which uses sshtunnel core and provide open several tunnels feature. (something like sshtunnels)

**Comment by fernandezcuesta** [comment]
Hi Pahaz,
The reason for opening several tunnels is a need I have to run a command at
the same time (actually with threads) in several systems behind a gateway
only for those that are reachable.
I studied your suggestion to build it on top of the current project, but
there are changes required everywhere in the code and it was far more
difficult to do it that way.
Particularly the check of both sides of the tunnels.
With your option I have to do open the tunnel several times, which is not a
problem but I preferred to make it more flexible (open N tunnels, where N
can be 1 which should work like with the original).

Anyway, feel free to reject it and/or adapt whatever you find interesting.

Regards

2015-02-23 19:09 GMT+01:00 Pahaz Blinov <notifications@github.com>:

**Comment by pahaz** [comment]
Big thangs! I merged it!

**Comment by fernandezcuesta** [comment]
Glad to see you found it useful.
By the way, I see you removed the retry with pkey when both (password, pkey) are given and password is rejected. Personally I found that useful, for example while logging in with preconfigured `~/.ssh/config` and mistyping the password in the CLI parameter.

**Pull request merged**
