### PR TITLE
Fixes orphan thread for a tunnel that is DOWN.

### LINKED ISSUE #170: Tunnel thread leakage with Python 3.6
If we try to establish SSH tunnel with connectivity checking to some service that is unavailable we will get thread leaking.

Here is the thing:

When sshtunnel.start() function is called it creates new thread that uses socketserver package serve_forever function as infinite loop that can be broken by setting special flag - __shutdown_request. This flag is set by sshtunnel module when we call it stop() function. The stop function sets __shutdown_request flag in the case when the tunnel_is_up flag are set.  If we check remote service availability and it's not available the tunnel_is_up flag is in False state and early created thread is not closed by stop method. The problem can be easily fixed this way:
```python
    def _stop_transport(self):
        """ Close the underlying transport when nothing more is needed """
        try:
            self._check_is_started()
        except (BaseSSHTunnelForwarderError,
                HandlerSSHTunnelForwarderError) as e:
            self.logger.warning(e)
        for _srv in self._server_list:
            tunnel = _srv.local_address
            if self.tunnel_is_up[tunnel]:
                self.logger.info('Shutting down tunnel {0}'.format(tunnel))
            _srv.shutdown()
            _srv.server_close()
            # clean up the UNIX domain socket if we're using one
            if isinstance(_srv, _UnixStreamForwardServer):
                try:
                    os.unlink(_srv.local_address)
                except Exception as e:
                    self.logger.error('Unable to unlink socket {0}: {1}'
                                      .format(self.local_address, repr(e)))
```

The problem can be easily reproduced by a code in the file: 

[thread_leaks_example.txt](https://github.com/pahaz/sshtunnel/files/3926069/thread_leaks_example.txt)

### PR DESCRIPTION
**Pull request by eddie-chiang**
Fixes #170

### CODE REVIEW

**Comment by pahaz** [comment]
Do you have any idea about how to test it?

**Comment by eddie-chiang** [comment]
> Do you have any idea about how to test it?

I think there is an example attached in https://github.com/pahaz/sshtunnel/issues/170 to reproduce the issue:
https://github.com/pahaz/sshtunnel/files/3926069/thread_leaks_example.txt

**Comment by pahaz** [comment]
> I think there is an example attached in #170 to reproduce the issue:
> https://github.com/pahaz/sshtunnel/files/3926069/thread_leaks_example.txt

I tried it. But I've got a different result

**Comment by eddie-chiang** [comment]
My minimum working example to illustrate the issue, TestIssue170.py, adapted from the previous example in #170:
```python
import logging
import threading
import time

from sshtunnel import HandlerSSHTunnelForwarderError, SSHTunnelForwarder

logging.basicConfig(level=logging.INFO)
# dutihr.st.ewi.tudelft.nl:27017 is not opened.
tunnel = SSHTunnelForwarder(('dutihr.st.ewi.tudelft.nl', 22),
                            ssh_username='ghtorrent',
                            ssh_pkey='<path_to_ssh_pkey>',
                            remote_bind_address=('dutihr.st.ewi.tudelft.nl', 27017),
                            logger=logging.getLogger('SSHTunnelForwarder'))

tunnel.skip_tunnel_checkup = False

try:
    print('Trying to open ssh tunnel...')
    tunnel.start()
except HandlerSSHTunnelForwarderError as e:
    print('Tunnel start exception: {}'.format(e))

try:
    print('Trying to close resources...')
    tunnel.stop()
except Exception as e:
    print('Resources closing exception: {}'.format(e))

print('Sleeping for 1 second...')
time.sleep(1)
current_threads = threading.enumerate()

print('Unclosed threads list: {}'.format(current_threads))
```

**Actual Behaviour:**

1. Generated logs:
```Shell Session
WARNING:SSHTunnelForwarder:Could not read SSH configuration file: ~/.ssh/config
INFO:SSHTunnelForwarder:0 keys loaded from agent
INFO:SSHTunnelForwarder:0 keys loaded from host directory
INFO:SSHTunnelForwarder:Connecting to gateway: dutihr.st.ewi.tudelft.nl:22 as user 'ghtorrent'
Trying to open ssh tunnel...
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.6p1)
INFO:paramiko.transport:Authentication (publickey) successful!
2020-10-24 06:38:00,206| ERROR   | Could not establish connection from ('127.0.0.1', 55059) to remote side of the tunnel
ERROR:SSHTunnelForwarder:Could not establish connection from ('127.0.0.1', 55059) to remote side of the tunnel
Tunnel start exception: An error occurred while opening tunnels.
Trying to close resources...
Sleeping for 1 second...
Unclosed threads list: [<_MainThread(MainThread, started 4708527552)>, <WriterThread(pydevd.Writer, started daemon 123145452924928)>, <ReaderThread(pydevd.Reader, started daemon 123145469714432)>, <_TimeoutThread(Thread-4, started daemon 123145486503936)>, <PyDBCommandThread(pydevd.CommandThread, started daemon 123145503293440)>, <CheckAliveThread(pydevd.CheckAliveThread, started 123145520082944)>, <Thread(Srv-55059, started 123145553661952)>]
```
Notice the ghost thread created at https://github.com/pahaz/sshtunnel/blob/f906d602df60bc4221b99cc049d3cac2880985e1/sshtunnel.py#L1299 
Unclosed threads list: [..., **<Thread(Srv-55059, started 123145553661952)>**

2. Also, the Python script is not terminated by the end of the execution. 


**Expected Behaviour (from the execution with the patch in the PR):**

1. Generated logs:

```Shell Session
WARNING:SSHTunnelForwarder:Could not read SSH configuration file: ~/.ssh/config
INFO:SSHTunnelForwarder:0 keys loaded from agent
INFO:SSHTunnelForwarder:0 keys loaded from host directory
INFO:SSHTunnelForwarder:Connecting to gateway: dutihr.st.ewi.tudelft.nl:22 as user 'ghtorrent'
Trying to open ssh tunnel...
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.6p1)
INFO:paramiko.transport:Authentication (publickey) successful!
2020-10-24 06:42:16,348| ERROR   | Could not establish connection from ('127.0.0.1', 55113) to remote side of the tunnel
ERROR:SSHTunnelForwarder:Could not establish connection from ('127.0.0.1', 55113) to remote side of the tunnel
Tunnel start exception: An error occurred while opening tunnels.
Trying to close resources...
Sleeping for 1 second...
Unclosed threads list: [<_MainThread(MainThread, started 4514250176)>, <WriterThread(pydevd.Writer, started daemon 123145538125824)>, <ReaderThread(pydevd.Reader, started daemon 123145554915328)>, <_TimeoutThread(Thread-4, started daemon 123145571704832)>, <PyDBCommandThread(pydevd.CommandThread, started daemon 123145588494336)>, <CheckAliveThread(pydevd.CheckAliveThread, started 123145605283840)>]
```

2. The "Srv-" thread created in SSHTunnelForwarder.start() should not appear in the unclosed threads list.
3. The Python script should be terminated by the end of the execution.

**Comment by pahaz** [comment]
Ow, I understand what's going on. as mention @kkrasovskii (here: https://github.com/pahaz/sshtunnel/issues/170)  it's better to just always call `_srv.shutdown()`.

And his proposal looks good to solve the problem.

**Comment by pahaz** [comment]
I've closed this PR because of https://github.com/pahaz/sshtunnel/pull/198 

I've added @eddie-chiang and @kkrasovskii to the contributor's list. 
Thanks!

**Pull request closed without merging**
